server:
  port: 8040

spring:
  application:
    name: boot-user-service-provider

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

  datasource:
    url: jdbc:mysql://localhost:3306/gmall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Haibo918116
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: boot-user-service-provider
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: nacos://127.0.0.1:8848
  monitor:
    protocol: registry
  scan:
    base-packages: com.fuwang.gmall.service